[env:esp32doit-devkit-v1]
platform = espressif32@6.5.0
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 240000000L  ; Overclock ke 240 MHz mutlak diperlukan untuk dekode audio yang stabil

lib_deps =
    ; Memanggil langsung pustaka master dari repositori pschatzmann
    https://github.com/pschatzmann/ESP32-A2DP.git#v1.7.0